[package]
name = "vraw_convert"
version = "0.4.0"
authors = [
    "Niclas Olmenius <niclas@voysys.se>", 
    "Jonathan Nilsson <jonathan@voysys.se>", 
    "Torkel Danielsson <torkel@voysys.se>", 
    "Viktor Kasimir <viktor@voysys.se>"]
publish = false
edition = "2021"

[dependencies]
byteorder = "1"
chrono = "0.4.5"
static_assertions = "1"
zerocopy = "0.6.1"
mp4 = "0.14.0"
clap = {version = "4.0.18", features = ["derive"] }
msgbox = "0.7.0"